version: "3.7"
x-ce_dev:
  version: 1.x
  registry: localhost:5000
  project_name: wikis2pages
  urls:
    - http://wikis2pages-hugo:4000/home
  provision: 
    - ce-dev/ansible/provision.yml
  deploy: 
    - ce-dev/ansible/deploy.yml
  ssh_hosts:
    - git.codeenigma.com
services:
  hugo:
    image: codeenigma/ce-dev-1.x:latest
    x-ce_dev: {}
    expose:
      - 4000
    volumes:
      - ../:/home/ce-dev/deploy/live.local