language: c
os: linux
dist: xenial
services:
  - docker
addons:
  apt:
    packages:
    - libnss3-tools
    - wget
install:
  - wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/mkcert-v1.4.1-linux-amd64 -O /tmp/mkcert
  - sudo mv /tmp/mkcert /usr/local/bin
  - sudo chmod +x /usr/local/bin/mkcert
  - curl -sL https://raw.githubusercontent.com/codeenigma/ce-dev/1.x/install.sh | /bin/sh -s -- linux
jobs:
  include:
    - name: Demo
      script: 
        - /bin/sh init.sh https://$GITHUB_TOKEN@github.com/pm98zz-c/wikis2pages-demo.git