- hosts: wikis2pages-hugo
  
  tasks:
    - include_vars:
        dir: wikis
        name: wikis

    - include_vars: current.yml

    - set_fact:
        wiki: "{{ wikis[current] | combine ({ 'name': current }) }}"

    - name: Generate config file.
      template:
        src: config.toml.j2
        dest: /home/ce-dev/deploy/live.local/config.toml

    - name: Add start/stop script.
      template:
        src: hugo-daemon.sh.j2
        dest: /opt/hugo-daemon.sh
        mode: 0755
      become: yes

    - name: Start hugo.
      command:
        cmd: /opt/hugo-daemon.sh start --detach