---
- hosts: wikis2pages-hugo
  become: true
  tasks:
    # CSS breaks after v0.122.0
    - name: Install Hugo
      ansible.builtin.apt:
        deb: https://github.com/gohugoio/hugo/releases/download/v0.122.0/hugo_extended_0.122.0_linux-amd64.deb
        state: present

    - ansible.builtin.include_vars:
        dir: wikis
        name: wikis

    - name: Generate the clone script.
      ansible.builtin.template:
        src: set-current.sh.j2
        dest: "{{ wiki2pages_build_path | default('/home/ce-dev/deploy/live.local') }}/set-current.sh"
        mode: 0775
