wiki:
  src: git@git.codeenigma.com:code-enigma/documentation/design-and-frontend-reference.wiki.git
  dest: design-and-frontend-reference.wiki
  branch: master
  subdir: ''
  title: Design and frontend reference